syntax = "proto3";

package userservice;

import "google/protobuf/timestamp.proto";

option go_package = "proto/userservicepb";

service UserService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc SignUp(SignUpRequest) returns (SignUpResponse);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc ReadUser(ReadUserRequest) returns (ReadUserResponse);
  rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse);
  rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);
}

message User{
  string id = 1;
  string email = 2;
  string full_name = 3;
  string role = 4;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string access_token = 1;
  google.protobuf.Timestamp access_expires_at = 2;
  string refresh_token = 3;
  google.protobuf.Timestamp refresh_expires_at = 4;
}

message SignUpRequest{
  string full_name = 1;
  string role = 2;
  string email = 3;
  string password = 4;
}

message SignUpResponse{
  string access_token = 1;
  google.protobuf.Timestamp access_expires_at = 2;
  string refresh_token = 3;
  google.protobuf.Timestamp refresh_expires_at = 4;
  User user = 5;
}

message RefreshRequest{
  string id = 1;
  string role = 2;
}

message RefreshResponse{
  string access_token = 1;
  google.protobuf.Timestamp access_expires_at = 2;
  string refresh_token = 3;
  google.protobuf.Timestamp refresh_expires_at = 4;
}

message ReadUserRequest{
  string id = 1;
}

message ReadUserResponse{
  User user = 1;
}

message UpdateUserRequest{
  string id = 1;
  string email = 2;
  string full_name = 3;
}

message UpdateUserResponse{
  User user = 1;
}

message ChangePasswordRequest{
  string id = 1;
  string password = 2;
}

message ChangePasswordResponse{
}